// Campus Eats — wireframe single source.
//
// One record per information block (one restaurant). Every page in the
// prototype is generated by selecting on these attributes; no restaurant
// is written into the HTML anywhere. To change the IA, edit this file only.
//
// Categories and labels come from the card sort report ("Card Sort Report:
// Categories + Labels") and the raw sorts in card_sorts.csv.
//
// verified: false marks a location/cuisine that was inferred from what most
// card sorters said, not checked against reality. Team: confirm and flip
// to true (or correct it).
window.CE_DATA = {
  title: "Campus Eats",
  tagline: "Find somewhere to eat on or near BYU campus.",

  // ---------------------------------------------------------------- view 1
  // Cuisine — strongest trend (~10 of 14 sorts). Working labels from the
  // report. Restaurants whose cuisine fits none of these have cuisine: []
  // and are reachable through Location only (allowed by the coverage rule).
  cuisines: [
    { key: "burgers", name: "Burgers" },
    { key: "pizza", name: "Pizza" },
    { key: "chicken", name: "Fried Chicken" },
    { key: "asian", name: "Asian" },
    { key: "mexican", name: "Mexican" },
    { key: "healthy", name: "Healthy" }
  ],

  // Level 2 of the cuisine view. BYU / not-BYU appeared in 5 of 14 sorts;
  // the report calls it a lower-level filter, not a top-level category.
  campus: [
    { key: "on", name: "On Campus" },
    { key: "near", name: "Near Campus" }
  ],

  // ---------------------------------------------------------------- view 2
  // Location — second trend (~6 of 14 sorts). L1 labels from the report.
  // On Campus has L2 areas using sort 1's own words ("Cougareat",
  // "North Campus", ...). The off-campus directions go straight to
  // restaurants.
  locations: [
    { key: "on-campus", name: "On Campus", campus: "on" },
    { key: "north", name: "North of Campus", campus: "near" },
    { key: "west", name: "West of Campus", campus: "near" },
    { key: "east", name: "East of Campus", campus: "near" },
    { key: "south", name: "South of Campus", campus: "near" }
  ],
  campusAreas: [
    { key: "cougareat", name: "Cougareat" },
    { key: "north-campus", name: "North Campus" },
    { key: "south-campus", name: "South Campus" },
    { key: "east-campus", name: "East Campus" },
    { key: "west-campus", name: "West Campus" }
  ],

  // ------------------------------------------------------------- the blocks
  // campus: "on" | "near"
  // area:   a campusAreas key when on campus, a locations key when near
  restaurants: [
    { id: "aloha-plate", name: "Aloha Plate", cuisine: [], campus: "on", area: "cougareat", verified: false },
    { id: "byu-creamery", name: "BYU Creamery", cuisine: ["burgers"], campus: "on", area: "east-campus", verified: false },
    { id: "blue-sushi", name: "Blue Sushi", cuisine: ["asian"], campus: "on", area: "cougareat", verified: false },
    { id: "burgers-supreme", name: "Burgers Supreme", cuisine: ["burgers"], campus: "near", area: "west", verified: false },
    { id: "chick-fil-a", name: "Chick-fil-A", cuisine: ["chicken"], campus: "on", area: "cougareat", verified: false },
    { id: "choices", name: "Choices", cuisine: ["healthy"], campus: "on", area: "cougareat", verified: false },
    { id: "costa-vida", name: "Costa Vida", cuisine: ["mexican"], campus: "on", area: "cougareat", verified: false },
    { id: "cougar-crust", name: "Cougar Crust", cuisine: ["pizza"], campus: "on", area: "cougareat", verified: false },
    { id: "crazy-ds", name: "Crazy D's Hot Chicken", cuisine: ["chicken"], campus: "near", area: "west", verified: false },
    { id: "cupbop", name: "Cupbop", cuisine: ["asian"], campus: "near", area: "south", verified: false },
    { id: "don-joaquin", name: "Don Joaquin Street Tacos", cuisine: ["mexican"], campus: "near", area: "west", verified: false },
    { id: "el-tio", name: "El Tio Tacos & More", cuisine: ["mexican"], campus: "near", area: "north", verified: false },
    { id: "greenhouse", name: "Greenhouse Salad Co.", cuisine: ["healthy"], campus: "near", area: "west", verified: false },
    { id: "harveys", name: "Harvey's", cuisine: ["burgers"], campus: "on", area: "south-campus", verified: false },
    { id: "j-dawgs", name: "J Dawgs", cuisine: [], campus: "near", area: "south", verified: false },
    { id: "jamba", name: "Jamba", cuisine: ["healthy"], campus: "on", area: "north-campus", verified: false },
    { id: "konala", name: "Konala", cuisine: ["healthy"], campus: "near", area: "west", verified: false },
    { id: "legends-grille", name: "Legends Grille", cuisine: [], campus: "on", area: "west-campus", verified: false },
    { id: "library-cafe", name: "Library Cafe", cuisine: [], campus: "on", area: "north-campus", verified: false },
    { id: "moa-cafe", name: "MOA Cafe", cuisine: [], campus: "on", area: "north-campus", verified: false },
    { id: "mo-bettahs", name: "Mo' Bettahs", cuisine: [], campus: "near", area: "north", verified: false },
    { id: "papa-johns", name: "Papa John's", cuisine: ["pizza"], campus: "on", area: "cougareat", verified: false },
    { id: "pendulum-court", name: "Pendulum Court Cafe", cuisine: [], campus: "on", area: "south-campus", verified: false },
    { id: "raising-canes", name: "Raising Cane's", cuisine: ["chicken"], campus: "near", area: "west", verified: false },
    { id: "ronis", name: "Roni's Mac Bar", cuisine: [], campus: "near", area: "west", verified: false },
    { id: "sage-pizza", name: "Sage Pizza", cuisine: ["pizza"], campus: "near", area: "east", verified: false },
    { id: "shirleys", name: "Shirley's Bakery & Cafe", cuisine: [], campus: "near", area: "north", verified: false },
    { id: "steak-express", name: "Steak Express", cuisine: [], campus: "near", area: "east", verified: false },
    { id: "subway", name: "Subway", cuisine: ["healthy"], campus: "on", area: "east-campus", verified: false },
    { id: "teri-gao", name: "Teri Gao Asian Cafe", cuisine: ["asian"], campus: "near", area: "west", verified: false },
    { id: "blue-line", name: "The Blue Line", cuisine: [], campus: "on", area: "north-campus", verified: false },
    { id: "taco-spot", name: "The Taco Spot", cuisine: ["mexican"], campus: "near", area: "west", verified: false },
    { id: "wendys", name: "Wendy's", cuisine: ["burgers"], campus: "on", area: "cougareat", verified: false },
    { id: "y-mountain-bbq", name: "Y Mountain BBQ", cuisine: [], campus: "on", area: "cougareat", verified: false }
  ],

  // ------------------------------------------------------- test scenarios
  // DRAFT — team to review. expect lists every restaurant that counts as a
  // correct answer. Scenarios avoid using the restaurant's name or the
  // exact category label where possible.
  tasks: [
    { id: "T01",
      scenario: "You're between classes in the Wilkinson Center and want fried chicken without leaving campus.",
      expect: ["chick-fil-a"] },
    { id: "T02",
      scenario: "Your study group wants to split a pizza, and nobody wants to leave campus.",
      expect: ["papa-johns", "cougar-crust"] },
    { id: "T03",
      scenario: "You live just off campus and are craving street tacos tonight. Find a place near campus.",
      expect: ["don-joaquin", "el-tio", "taco-spot"] },
    { id: "T04",
      scenario: "You've been studying in the library all afternoon and want a coffee-shop-style lunch close by.",
      expect: ["library-cafe", "moa-cafe"] },
    { id: "T05",
      scenario: "You're trying to eat better this week. Find something healthy you can get on campus.",
      expect: ["jamba", "choices", "subway"] },
    { id: "T06",
      scenario: "A friend wants to meet for mac and cheese at a place west of campus. Find it.",
      expect: ["ronis"] },
    { id: "T07",
      scenario: "You're headed south of campus and want a Korean rice bowl.",
      expect: ["cupbop"] },
    { id: "T08",
      scenario: "You want a burger, but somewhere off campus for a change.",
      expect: ["burgers-supreme"] },
    { id: "T09",
      scenario: "You're already at the Cougareat and you're in the mood for barbecue.",
      expect: ["y-mountain-bbq"] },
    { id: "T10",
      scenario: "You want sushi and only have twenty minutes, so it has to be on campus.",
      expect: ["blue-sushi"] }
  ]
};
